config/routes.rb
Rails.application.routes.draw do
  resources :posts

  root 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.all.order('created_at DESC').paginate(page: params[:page], per_page: 2)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to @post, notice: "Post successfuly created!"
		else
			render 'new', notice: "Unable to save the post"
		end
	end

	def show
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	def edit

	end

	def update
		if @post.update post_params
			redirect_to @post, notice: "Post updated successfuly!"
		else
			render 'show'
		end
	end



	private

	def find_post
		@post = Post.friendly.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :content, :slug)
	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.all.order('created_at DESC')
	end

	def show
		@post = Post.friendly.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class HTMLwithPygments < Redcarpet::Render::HTML
		def block_code(code, language)
			Pygments.highlight(code, lexer: language)
		end
	end
	
	def markdown(content)
		renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
			no_intra_emphasis: true,
			disable_indented_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <link href='//fonts.googleapis.com/css?family=Libre+Baskerville' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header id="main_navigation" class="clearfix">
      <%= link_to "Eduardo Martins", root_path, class: "name" %>
      
      <nav>
      	<%= link_to "My Blog", posts_path %>
        <a href="#">My projects</a>
        <a href="contact.html">Contact me</a>
      </nav>
    </header>


	<%= yield %>

<br>

<footer class="my-footer">
	<div id="main-footer">
	   <p class="copyright">&copy; 2016 Eduardo Martins</p>
	   <nav>
	     <a href="#"><i class="fa fa-twitter"></i></a>
	     <a href="#"><i class="fa fa-bitbucket"></i></a>
	     <a href="#"><i class="fa fa-github"></i></a>
	   </nav>
	 </div>
</footer>


</body>
</html>

app/views/posts/_comments.html.erb
<div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/

var disqus_shortname = 'eduardomartinsblog';
var disqus_identifier = '<%= @post.id %>';
var disqus_title = '<%= @post.title %>';
var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//eduardomartinsblog.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
	= f.input :title
	= f.input :content
	= f.submit

app/views/posts/edit.html.haml
.skinny_wrapper.wrapper_padding
	%h1 Update your post
	= render'form'

app/views/posts/index.html.haml
%h1#page_title Stuffs I've writing

- @posts.each do |post|
	#post_wrapper.skinny_wrapper
		.post
			%p.date= post.created_at.strftime("%d %b %Y")
			%h2= link_to post.title, post_path(post.id)
			%hr


= will_paginate @posts


= link_to "Create a Post", new_post_path, class: "button"

app/views/posts/new.html.haml
.skinny_wrapper.wrapper_padding
	%h1 Create a new post
	= render 'form'

app/views/posts/show.html.haml
#post_show_content.skinny_wrapper.wrapper_padding
	%header
		%p.date= @post.created_at.strftime("%d %b %Y")
		%h1= @post.title
		%hr/
	#content
		= markdown(@post.content).html_safe
		%hr/
		%br/
		%br/
	#share_box
		%p= "Share the: #{@post.title}" 
		
		.twitter
			%a.twitter-share-button.left{"data-count" => "horizontal", "data-via" => "ffwdesign", :href => "http://twitter.com/share"} Tweet
			%script{:src => "http://platform.twitter.com/widgets.js", :type => "text/javascript"}

	%hr
	= render 'comments'

    


= link_to "Back", posts_path

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
      <div class="col-1 about homepage_content">
        <h2>About</h2>
        <hr>
        <p>I'm a designer &amp; developer based on Brazil. I have a passion for dessign and technology.</p>
        <p>Actualy by day I work as a consultant for the TOTVS company. At night I develop web applications with Ruby on Rails and do some design stuff.</p>
        <p>On my blog a teach some useful tips and tricks about design and web development.</p>
      </div>
      <div class="col-2 homepage_content">
        <h2>Stuffs I've written</h2>
        <hr>
        <% @posts.take(3).each do |post| %>
          <h3 class="post"><%= link_to post.title, post_path(post.id)%></h3>
          <p class:"date"><%= post.created_at.strftime("%d %b %Y") %></p>
        <% end %>
      </div>
      <div class="col-3 homepage_content">
        <h2>Stuffs I've built</h2>
        <hr>
        <h3>My note app</h3>
        <p class="date">Friday Apreil 10th</p>
        <h3>Tellme app</h3>
        <p class="date">Friday Apreil 10th</p>
        <h3>Some another app</h3>
        <p class="date">Friday Apreil 10th</p>
      </div>
</div>